name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: setup env
      run: |
        apt-get update --fix-missing
        apt-get install -y git curl wget
    - name: test
      run: sh boostrap.sh
