name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup env
      run: |
        apt-get update --fix-missing
        apt-get install -y git curl wget
        rm -rf /tmp/*
    - name: Test
      run: sh bootstrap.sh
